server:
  port: 8081
spring:
  r2dbc:
    url: 'r2dbc:mysql://122.9.33.79:3307/myblog'
    username: root
    password: 1157
    pool:
      enabled: true
      initial-size: 1
      validation-query: select 1
      max-life-time: 10000

  jackson:
    default-property-inclusion: non_null